-- ==============================================================================
-- Migration: 20260911000001_initial_schema.sql
-- Description: DDL inicial do banco de dados ControlAI (SaaS Multi-tenant BYOK)
-- Author: ControlAI Architect
-- ==============================================================================

-- 1. Habilitar extensões necessárias
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Tipos e Enums
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('master', 'admin', 'user');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'company_status') THEN
    CREATE TYPE company_status AS ENUM ('trialing', 'active', 'past_due', 'canceled', 'incomplete');
  END IF;
END $$;

-- 3. Tabela: planos
CREATE TABLE IF NOT EXISTS public.planos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE,
  preco_mensal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  max_usuarios INTEGER NOT NULL DEFAULT 1,
  max_agentes INTEGER NOT NULL DEFAULT 1,
  limite_mensagens_mes INTEGER NOT NULL DEFAULT 100,
  stripe_price_id VARCHAR(255) UNIQUE,
  features JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  cor VARCHAR(50) DEFAULT 'hsl(166, 100%, 50%)',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. Tabela: empresas (Tenants)
CREATE TABLE IF NOT EXISTS public.empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  plano_id BIGINT REFERENCES public.planos(id) ON DELETE SET NULL,
  chave_api_llm TEXT, -- Armazenado criptografado via pgcrypto
  chave_api_mascarada VARCHAR(50), -- Ex: "sk-...1234" para exibição segura na UI
  contexto_ia JSONB DEFAULT '{"regras": "", "modo": "padrao", "temperatura": 0.7}'::jsonb,
  stripe_customer_id VARCHAR(255) UNIQUE,
  email VARCHAR(255),
  telefone VARCHAR(50),
  endereco TEXT,
  status company_status NOT NULL DEFAULT 'trialing',
  data_adesao TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  proxima_cobranca TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. Tabela: perfis (Usuários / Colaboradores vinculados a auth.users e empresas)
CREATE TABLE IF NOT EXISTS public.perfis (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  role user_role NOT NULL DEFAULT 'user',
  email VARCHAR(255) NOT NULL,
  nome_completo VARCHAR(255) NOT NULL,
  telefone VARCHAR(50),
  cargo VARCHAR(100),
  status VARCHAR(50) NOT NULL DEFAULT 'ativo',
  ultimo_acesso TIMESTAMPTZ,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 6. Tabela: agentes_ia
CREATE TABLE IF NOT EXISTS public.agentes_ia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  instrucoes TEXT NOT NULL,
  icone_url TEXT,
  descricao TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_popular BOOLEAN NOT NULL DEFAULT false,
  cor VARCHAR(50) DEFAULT 'hsl(166, 100%, 50%)',
  created_by UUID REFERENCES public.perfis(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 7. Tabela: conversas (Histórico de Chats)
CREATE TABLE IF NOT EXISTS public.conversas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.perfis(id) ON DELETE CASCADE,
  agente_id BIGINT REFERENCES public.agentes_ia(id) ON DELETE SET NULL,
  mensagens JSONB NOT NULL DEFAULT '[]'::jsonb,
  titulo VARCHAR(255) NOT NULL DEFAULT 'Nova Conversa',
  tokens_usados INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'ativa',
  contexto_atual JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 8. Tabela: uso_recursos (Controle de Limites por Mês e por Tenant)
CREATE TABLE IF NOT EXISTS public.uso_recursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  mes_referencia DATE NOT NULL,
  mensagens_enviadas INTEGER NOT NULL DEFAULT 0,
  tokens_consumidos INTEGER NOT NULL DEFAULT 0,
  agentes_ativos INTEGER NOT NULL DEFAULT 0,
  usuarios_ativos INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT unq_empresa_mes UNIQUE (empresa_id, mes_referencia)
);

-- 9. Tabela: auditoria (Logs de Ações Administrativas)
CREATE TABLE IF NOT EXISTS public.auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.perfis(id) ON DELETE SET NULL,
  empresa_id BIGINT REFERENCES public.empresas(id) ON DELETE CASCADE,
  acao VARCHAR(100) NOT NULL,
  entidade_tipo VARCHAR(100) NOT NULL,
  entidade_id VARCHAR(100),
  detalhes JSONB DEFAULT '{}'::jsonb,
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 10. Índices para Otimização de Performance Multi-tenant
CREATE INDEX IF NOT EXISTS idx_empresas_plano_id ON public.empresas(plano_id);
CREATE INDEX IF NOT EXISTS idx_empresas_stripe_customer_id ON public.empresas(stripe_customer_id);

CREATE INDEX IF NOT EXISTS idx_perfis_empresa_id ON public.perfis(empresa_id);
CREATE INDEX IF NOT EXISTS idx_perfis_role ON public.perfis(role);
CREATE INDEX IF NOT EXISTS idx_perfis_email ON public.perfis(email);

CREATE INDEX IF NOT EXISTS idx_agentes_ia_empresa_id ON public.agentes_ia(empresa_id);
CREATE INDEX IF NOT EXISTS idx_agentes_ia_is_active ON public.agentes_ia(is_active);

CREATE INDEX IF NOT EXISTS idx_conversas_empresa_id ON public.conversas(empresa_id);
CREATE INDEX IF NOT EXISTS idx_conversas_user_id ON public.conversas(user_id);
CREATE INDEX IF NOT EXISTS idx_conversas_agente_id ON public.conversas(agente_id);
CREATE INDEX IF NOT EXISTS idx_conversas_uuid ON public.conversas(conversation_uuid);

CREATE INDEX IF NOT EXISTS idx_uso_recursos_empresa_mes ON public.uso_recursos(empresa_id, mes_referencia);
CREATE INDEX IF NOT EXISTS idx_auditoria_empresa_id ON public.auditoria(empresa_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_user_id ON public.auditoria(user_id);

-- 11. Carga Inicial de Planos (Seed Data)
INSERT INTO public.planos (nome, preco_mensal, max_usuarios, max_agentes, limite_mensagens_mes, stripe_price_id, features, is_active, cor)
VALUES
  (
    'Free',
    0.00,
    1,
    1,
    100,
    NULL,
    '["1 Usuário", "1 Agente IA", "Até 100 msgs/mês", "Suporte Comunitário"]'::jsonb,
    true,
    'hsl(0, 0%, 60%)'
  ),
  (
    'Básico',
    99.00,
    5,
    3,
    5000,
    'price_basic_monthly',
    '["Até 5 Usuários", "3 Agentes IA Customizados", "5.000 msgs/mês", "Chave BYOK OpenAI/Claude", "Suporte por Email"]'::jsonb,
    true,
    'hsl(166, 100%, 50%)'
  ),
  (
    'Empresa',
    299.00,
    25,
    10,
    25000,
    'price_enterprise_monthly',
    '["Até 25 Usuários", "10 Agentes IA Customizados", "25.000 msgs/mês", "Chave BYOK OpenAI/Claude", "Logs de Auditoria", "Suporte Prioritário"]'::jsonb,
    true,
    'hsl(42, 100%, 48%)'
  ),
  (
    'Master',
    899.00,
    100,
    50,
    100000,
    'price_master_monthly',
    '["Até 100 Usuários", "50 Agentes IA", "100.000 msgs/mês", "BYOK Ilimitado", "Auditoria Completa", "Gerente de Conta Dedicado"]'::jsonb,
    true,
    'hsl(280, 100%, 60%)'
  )
ON CONFLICT (nome) DO UPDATE SET
  preco_mensal = EXCLUDED.preco_mensal,
  max_usuarios = EXCLUDED.max_usuarios,
  max_agentes = EXCLUDED.max_agentes,
  limite_mensagens_mes = EXCLUDED.limite_mensagens_mes,
  features = EXCLUDED.features,
  cor = EXCLUDED.cor;
